export const ALLOWED_FONTS = [
  "Inter",
  "Space Grotesk",
  "Playfair Display",
  "DM Serif Display",
  "Manrope",
  "Merriweather",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Nunito",
  "Raleway",
  "DM Sans",
  "Outfit",
  "Plus Jakarta Sans",
  "Fugaz One",
];

export const HEX_COLOR_REGEX = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;

export const RADIUS_MAP = {
  sharp: "0px",
  soft: "4px",
  editorial: "10px",
  rounded: "16px",
};

export const SPACING_MAP = {
  compact: { container: "1rem", section: "2rem", card: "0.75rem" },
  cozy: { container: "2rem", section: "4rem", card: "1.5rem" },
  airy: { container: "3rem", section: "6rem", card: "2rem" },
};

export const DEFAULT_SECTIONS = [
  { sectionId: "hero", visible: true, order: 1 },
  { sectionId: "projects", visible: true, order: 2 },
  { sectionId: "about", visible: true, order: 3 },
  { sectionId: "experience", visible: true, order: 4 },
  { sectionId: "education", visible: true, order: 5 },
  { sectionId: "skills", visible: true, order: 6 },
  { sectionId: "practice", visible: true, order: 7 },
  { sectionId: "goals", visible: true, order: 8 },
  { sectionId: "contact", visible: true, order: 9 },
];

export const DEFAULT_LIGHT_COLORS = {
  primary: "#FFFFFF",
  accent: "#0284C7",
  background: "#F8FAFC",
  text: "#334155",
  headingColor: "#0F172A",
  cardBg: "#FFFFFF",
};

export const DEFAULT_CONTENT = {
  navbar: {
    brandTitle: "Muhammad Waqar",
    brandInitials: "MW",
    resumeText: "Resume ↗",
    linkWork: "Selected Work",
    linkAbout: "About",
    linkExperience: "Experience",
    linkSkills: "Skills",
    linkPractice: "Practice Lab",
    linkContact: "Contact",
  },
  hero: {
    edition: "PORTFOLIO // 2026",
    specialization: "FULL-STACK WEB SYSTEMS",
    location: "BASED IN PAKISTAN — OPEN GLOBALLY",
    roleTag: "Software Engineer & Full-Stack Developer",
    name: "Muhammad Waqar",
    bio: "I engineer fast, scalable web software and thoughtful user interfaces with modern React, Next.js, and Node.js architectures.",
    buttonPrimary: "Explore Work ↓",
    buttonSecondary: "Get in Touch →",
    currentFocus: "Next.js App Router, Scalable Full-Stack Systems, and Database Architectures",
    coreStack: "React, Next.js, Node.js, Express, MongoDB, Tailwind CSS",
    philosophy: "Clean code, intuitive user interfaces, and attention to detail.",
    status: "Available for new opportunities",
  },
  about: {
    tagline: "Background & Philosophy",
    heading: "Engineering with clarity and intention.",
    paragraph1: "I am a Full Stack Engineer dedicated to producing fast, accessible, and scalable web software. My focus centers on modern JavaScript, React, Next.js, and cloud-native database architectures.",
    paragraph2: "Rather than treating styling and backend as separate concerns, I engineer applications from database schema to pixel-perfect component rendering, ensuring every layer is maintainable, solo-operable, and crawlable by search engines.",
    principles: [
      {
        label: "ARCHITECTURE",
        title: "Resilient & Scalable Systems",
        description: "Building modular, decoupled component systems and clean data flows that grow effortlessly with product complexity without accumulating technical debt.",
      },
      {
        label: "PERFORMANCE",
        title: "Sub-Second Latency & Fast Rendering",
        description: "Prioritizing Core Web Vitals, server-side caching, aggressive font optimization, and minimal layout shifts to deliver immediate user responsiveness.",
      },
      {
        label: "CRAFTSMANSHIP",
        title: "Pixel Precision & Clean Interfaces",
        description: "Designing accessible, responsive interfaces with strict adherence to typographic scale, contrast ratios, and purposeful micro-interactions.",
      },
    ],
  },
  sectionHeaders: {
    projectsTagline: "Curated Work",
    projectsHeading: "Featured Projects",
    practiceTagline: "Secondary Showcase",
    practiceHeading: "Practice & Exploratory Lab",
    experienceTagline: "Work History",
    experienceHeading: "Professional Experience",
    educationTagline: "Academic Credentials",
    educationHeading: "Formal Education",
    skillsTagline: "Capabilities",
    skillsHeading: "Technical Skills",
  },
  goals: {
    tagline: "Trajectory",
    heading: "Engineering Trajectory & 2026 Focus",
    paragraph1: "Currently deepening production capabilities in Next.js App Router architectures, distributed Node/Express micro-APIs, and low-latency database indexing with MongoDB.",
    commitment: "COMMITTED TO: Strict semantic HTML5 · Zero CLS · Verified accessibility · Solo-maintainable architectures.",
  },
  footer: {
    builtWithText: "BUILT WITH NEXT.JS APP ROUTER · TAILWIND CSS · MONGOOSE",
  },
};

export const THEME_PRESETS = {
  "preset-1": {
    id: "preset-1",
    name: "Cyber Cyan Arcade",
    subtitle: "Electric Cyan · Hex Grid · Fugaz One",
    description: "Interactive cyber portfolio with animated honeycomb canvas, trailing snake cursor, dual-layer stroke titles, and neon glow-box tech stack.",
    badge: "Cyber Cyan",
    colors: {
      primary: "#06090e",
      accent: "#1fc3ff",
      background: "#06090e",
      text: "#d1d5db",
      headingColor: "#ffffff",
      cardBg: "#0a0f19",
    },
    lightColors: {
      primary: "#06090e",
      accent: "#1fc3ff",
      background: "#06090e",
      text: "#d1d5db",
      headingColor: "#ffffff",
      cardBg: "#0a0f19",
    },
    typography: {
      headingFont: "Fugaz One",
      bodyFont: "Open Sans",
    },
    radius: "rounded",
    spacing: "cozy",
    sections: [
      { sectionId: "hero", visible: true, order: 1 },
      { sectionId: "about", visible: true, order: 2 },
      { sectionId: "skills", visible: true, order: 3 },
      { sectionId: "projects", visible: true, order: 4 },
      { sectionId: "experience", visible: true, order: 5 },
      { sectionId: "education", visible: true, order: 6 },
      { sectionId: "contact", visible: true, order: 7 },
      { sectionId: "practice", visible: false, order: 8 },
      { sectionId: "goals", visible: false, order: 9 },
    ],
    content: DEFAULT_CONTENT,
  },
  "preset-2": {
    id: "preset-2",
    name: "Obsidian & Crimson Studio",
    subtitle: "Pitch Dark · Crimson Red Accent · Bento Architecture",
    description: "Modern high-end dark portfolio inspired by abhayrana.com with obsidian canvas (#0a0a0a), crimson red (#ef4444) highlights, drifting starfield, cursor follower, mouse-parallax ambient glow, and bento project cards.",
    badge: "Obsidian Crimson",
    colors: {
      primary: "#0a0a0a",
      accent: "#ef4444",
      background: "#0a0a0a",
      text: "#a1a1aa",
      headingColor: "#fafafa",
      cardBg: "#121214",
      highlight: "#f97316",
      border: "#27272a",
      accentGlow: "#ef44444d",
      deepDark: "#050505",
      zinc900: "#18181b",
    },
    lightColors: {
      primary: "#0a0a0a",
      accent: "#ef4444",
      background: "#0a0a0a",
      text: "#a1a1aa",
      headingColor: "#fafafa",
      cardBg: "#121214",
      highlight: "#f97316",
      border: "#27272a",
      accentGlow: "#ef44444d",
    },
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
    },
    radius: "rounded",
    spacing: "cozy",
    sections: [
      { sectionId: "hero", visible: true, order: 1 },
      { sectionId: "about", visible: true, order: 2 },
      { sectionId: "projects", visible: true, order: 3 },
      { sectionId: "skills", visible: true, order: 4 },
      { sectionId: "experience", visible: true, order: 5 },
      { sectionId: "contact", visible: true, order: 6 },
      { sectionId: "education", visible: false, order: 7 },
      { sectionId: "practice", visible: false, order: 8 },
      { sectionId: "goals", visible: false, order: 9 },
    ],
    content: {
      navbar: {
        brandTitle: "Muhammad.",
        brandInitials: "MW",
        resumeText: "Resume",
        linkHome: "Home",
        linkAbout: "About",
        linkWork: "Projects",
        linkSkills: "Skills",
        linkExperience: "Experience",
        linkPractice: "",
        linkContact: "Contact",
      },
      hero: {
        edition: "Hey, I'm",
        specialization: "FULL STACK DEVELOPER",
        location: "Pakistan — Available Globally",
        roleTag: "Full Stack Developer",
        name: "Muhammad Waqar",
        bio: "I build and craft digital experiences that deliver real impact",
        buttonPrimary: "Let's Connect →",
        buttonSecondary: "mwaqar7615@gmail.com",
        currentFocus: "Turning Ideas into Digital Solutions",
        coreStack: "React, Next.js, Node.js, Express, MongoDB, Tailwind CSS",
        philosophy: "Clean code, intuitive user interfaces, and attention to detail.",
        status: "Available for new opportunities",
      },
      about: {
        tagline: "About Me",
        heading: "Get to know me better",
        paragraph1: "I'm a passionate Full Stack Developer who loves turning ideas into real, functional, and user-friendly web applications. I enjoy working across the entire web ecosystem and constantly learning new technologies to stay ahead.",
        paragraph2: "Whether engineering real-time inventory systems, modern e-commerce experiences, or scalable API architectures, I focus on craftsmanship, performant code, and intuitive user experiences.",
        badge1: "Clean Code",
        badge2: "Problem Solver",
        badge3: "Fast Execution",
        profileName: "Muhammad Waqar",
        profileLocation: "Pakistan",
        profileEmail: "mwaqar7615@gmail.com",
        profileExperience: "2+ Years Experience",
      },
      skills: {
        tagline: "Skills",
        heading: "Technologies and tools I use to build products",
        subtext: "A curated overview of my primary stack across frontend, backend, databases, and DevOps.",
      },
      sectionHeaders: {
        projectsTagline: "Projects",
        projectsHeading: "Some of the things I've built",
        projectsButton: "View All Projects →",
        contactTagline: "Want to know more?",
        contactHeading: "Let's build something great together",
        contactSubtext: "I'm always open to discussing new projects, engineering challenges, or potential collaborations. Feel free to reach out!",
        experienceTagline: "Experience",
        experienceHeading: "My professional journey so far",
        educationTagline: "Academic Background",
        educationHeading: "Education & Credentials",
        skillsTagline: "Skills",
        skillsHeading: "Technologies and tools I use to build products",
      },
      goals: {
        tagline: "Looking Ahead",
        heading: "Engineering Trajectory & 2026 Focus",
        paragraph1: "Continuously deepening expertise in Next.js App Router, real-time microservices, and distributed cloud systems.",
        commitment: "COMMITTED TO: Clean code · High performance · Responsive UX · Accessible design.",
      },
      footer: {
        builtWithText: "© 2026 Muhammad Waqar. All rights reserved.",
      },
    },
  },
};

export const DEFAULT_THEME = {
  presetId: "preset-2",
  status: "published",
  colors: { ...THEME_PRESETS["preset-2"].colors },
  lightColors: { ...THEME_PRESETS["preset-2"].lightColors },
  content: { ...THEME_PRESETS["preset-2"].content },
  typography: { ...THEME_PRESETS["preset-2"].typography },
  radius: THEME_PRESETS["preset-2"].radius,
  spacing: THEME_PRESETS["preset-2"].spacing,
  sections: [...THEME_PRESETS["preset-2"].sections],
  history: [],
};

export const FONT_VARIABLE_MAP = {
  "Inter": "var(--font-inter), sans-serif",
  "Space Grotesk": "var(--font-space-grotesk), sans-serif",
  "Playfair Display": "var(--font-playfair-display), serif",
  "DM Serif Display": "var(--font-dm-serif-display), serif",
  "Manrope": "var(--font-manrope), sans-serif",
  "Merriweather": "var(--font-merriweather), serif",
  "Roboto": "var(--font-roboto), sans-serif",
  "Open Sans": "var(--font-open-sans), sans-serif",
  "Lato": "var(--font-lato), sans-serif",
  "Montserrat": "var(--font-montserrat), sans-serif",
  "Poppins": "var(--font-poppins), sans-serif",
  "Nunito": "var(--font-nunito), sans-serif",
  "Raleway": "var(--font-raleway), sans-serif",
  "DM Sans": "var(--font-dm-sans), sans-serif",
  "Outfit": "var(--font-outfit), sans-serif",
  "Plus Jakarta Sans": "var(--font-plus-jakarta-sans), sans-serif",
  "Fugaz One": "'Fugaz One', cursive, sans-serif",
};
