export const ALLOWED_FONTS = [
  "Inter",
  "Space Grotesk",
  "Playfair Display",
  "DM Serif Display",
  "Manrope",
  "Merriweather",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Nunito",
  "Raleway",
  "DM Sans",
  "Outfit",
  "Plus Jakarta Sans",
];

export const HEX_COLOR_REGEX = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;

export const RADIUS_MAP = {
  sharp: "0px",
  soft: "4px",
  editorial: "10px",
  rounded: "16px",
};

export const SPACING_MAP = {
  compact: { container: "1rem", section: "2rem", card: "0.75rem" },
  cozy: { container: "2rem", section: "4rem", card: "1.5rem" },
  airy: { container: "3rem", section: "6rem", card: "2rem" },
};

export const DEFAULT_SECTIONS = [
  { sectionId: "hero", visible: true, order: 1 },
  { sectionId: "projects", visible: true, order: 2 },
  { sectionId: "about", visible: true, order: 3 },
  { sectionId: "experience", visible: true, order: 4 },
  { sectionId: "education", visible: true, order: 5 },
  { sectionId: "skills", visible: true, order: 6 },
  { sectionId: "practice", visible: true, order: 7 },
  { sectionId: "goals", visible: true, order: 8 },
  { sectionId: "contact", visible: true, order: 9 },
];

export const DEFAULT_LIGHT_COLORS = {
  primary: "#FFFFFF",
  accent: "#0284C7",
  background: "#F8FAFC",
  text: "#334155",
  headingColor: "#0F172A",
  cardBg: "#FFFFFF",
};

export const DEFAULT_CONTENT = {
  navbar: {
    brandTitle: "Muhammad Waqar",
    brandInitials: "MW",
    resumeText: "Resume ↗",
    linkWork: "Selected Work",
    linkAbout: "About",
    linkExperience: "Experience",
    linkSkills: "Skills",
    linkPractice: "Practice Lab",
    linkContact: "Contact",
  },
  hero: {
    edition: "PORTFOLIO EDITION // 2026",
    specialization: "SPECIALIZATION: FRONTEND & FULL-STACK SYSTEMS",
    location: "BASED IN PAKISTAN — OPEN GLOBALLY",
    roleTag: "Software Engineer & Interface Craftsman",
    name: "Muhammad Waqar",
    bio: "I engineer resilient frontend architectures, intuitive user interfaces, and full-stack web applications with React, Next.js, and modern TypeScript. Bridging design precision with performance-driven engineering.",
    buttonPrimary: "Explore Selected Work ↓",
    buttonSecondary: "Initiate Conversation →",
    currentFocus: "Next.js SSR/ISR, React Server Components, and Scalable Full-Stack Systems",
    coreStack: "React, Next.js, Node.js, Express, MongoDB, Tailwind CSS",
    philosophy: "Zero bloated abstractions. Semantic HTML, fast first-byte rendering, accessible UI patterns, and maintainable data models.",
    status: "Active & Open to Opportunities",
  },
  about: {
    tagline: "Background & Philosophy",
    heading: "Engineering with clarity and intention.",
    paragraph1: "I am a Frontend & Full-Stack Engineer dedicated to producing fast, accessible, and scalable web software. My focus centers on modern JavaScript, React, Next.js, and cloud-native database architectures.",
    paragraph2: "Rather than treating styling and backend as separate concerns, I engineer applications from database schema to pixel-perfect component rendering, ensuring every layer is maintainable, solo-operable, and crawlable by search engines.",
    principles: [
      {
        label: "PRINCIPLE 01 // ARCHITECTURE",
        title: "Resilient & Scalable Systems",
        description: "Building modular, decoupled component systems and clean data flows that grow effortlessly with product complexity without accumulating technical debt.",
      },
      {
        label: "PRINCIPLE 02 // PERFORMANCE",
        title: "Sub-Second Latency & Zero FOUC",
        description: "Prioritizing Core Web Vitals, server-side caching, aggressive font optimization, and minimal layout shifts to deliver immediate user responsiveness.",
      },
      {
        label: "PRINCIPLE 03 // CRAFTSMANSHIP",
        title: "Pixel Precision & Ergonomics",
        description: "Designing accessible, responsive interfaces with strict adherence to typographic scale, contrast ratios, and purposeful micro-interactions.",
      },
    ],
  },
  sectionHeaders: {
    projectsTagline: "Curated Production Work",
    projectsHeading: "Featured Projects",
    practiceTagline: "Secondary Showcase",
    practiceHeading: "Practice & Exploratory Lab",
    experienceTagline: "Work History",
    experienceHeading: "Professional Experience",
    educationTagline: "Academic Credentials",
    educationHeading: "Formal Education",
    skillsTagline: "Technical Matrix",
    skillsHeading: "Core Competencies",
  },
  goals: {
    tagline: "Trajectory",
    heading: "Engineering Trajectory & 2026 Focus",
    paragraph1: "Currently deepening production capabilities in Next.js App Router architectures, distributed Node/Express micro-APIs, and low-latency database indexing with MongoDB.",
    commitment: "COMMITTED TO: Strict semantic HTML5 · Zero CLS · Verified accessibility · Solo-maintainable architectures.",
  },
  footer: {
    builtWithText: "BUILT WITH NEXT.JS APP ROUTER · TAILWIND CSS · MONGOOSE",
  },
};

export const THEME_PRESETS = {
  "preset-1": {
    id: "preset-1",
    name: "Technical Craftsman",
    subtitle: "Cyber / Engineering / Cyan Accent",
    description: "High-precision technical architecture with monospace index bars, cyan highlights, and crisp geometric cards.",
    badge: "Technical",
    colors: {
      primary: "#090A0F",
      accent: "#38BDF8",
      background: "#090A0F",
      text: "#F8FAFC",
      headingColor: "#FFFFFF",
      cardBg: "#0C0E14",
    },
    lightColors: {
      primary: "#FFFFFF",
      accent: "#0284C7",
      background: "#F8FAFC",
      text: "#334155",
      headingColor: "#0F172A",
      cardBg: "#FFFFFF",
    },
    typography: {
      headingFont: "Space Grotesk",
      bodyFont: "Inter",
    },
    radius: "soft",
    spacing: "cozy",
    content: DEFAULT_CONTENT,
  },
  "preset-2": {
    id: "preset-2",
    name: "Warm Studio / Earthy Editorial",
    subtitle: "Charcoal & Ivory · DM Serif Display + Manrope",
    description: "An art-directed editorial developer portfolio combining Charcoal (#151713) and Warm Ivory (#F2EEE5) sections, serif typography, photo hero, 4-column skills, and 3-column project cards.",
    badge: "Editorial Studio",
    colors: {
      primary: "#151713",
      accent: "#D8B894",
      background: "#151713",
      text: "#C5C4BC",
      headingColor: "#F4F0E8",
      cardBg: "#181A15",
      highlight: "#E8B58F",
      olive: "#69745A",
      muted: "#77766D",
      border: "#383A33",
      deepDark: "#0D0F0D",
      warmIvory: "#F2EEE5",
      creamCard: "#ECE7DC",
    },
    lightColors: {
      primary: "#F2EEE5",
      accent: "#D8B894",
      background: "#F2EEE5",
      text: "#5F5E57",
      headingColor: "#191A17",
      cardBg: "#ECE7DC",
      highlight: "#E8B58F",
      olive: "#69745A",
      muted: "#77766D",
      border: "#D3CEC2",
      deepDark: "#0D0F0D",
    },
    typography: {
      headingFont: "DM Serif Display",
      bodyFont: "Manrope",
    },
    radius: "editorial",
    spacing: "cozy",
    sections: [
      { sectionId: "hero", visible: true, order: 1 },
      { sectionId: "about", visible: true, order: 2 },
      { sectionId: "skills", visible: true, order: 3 },
      { sectionId: "projects", visible: true, order: 4 },
      { sectionId: "contact", visible: true, order: 5 },
      { sectionId: "experience", visible: false, order: 6 },
      { sectionId: "education", visible: false, order: 7 },
      { sectionId: "practice", visible: false, order: 8 },
      { sectionId: "goals", visible: false, order: 9 },
    ],
    content: {
      navbar: {
        brandTitle: "MUHAMMAD WAQAR",
        brandInitials: "MW",
        resumeText: "Download CV",
        linkWork: "Projects",
        linkAbout: "About",
        linkExperience: "",
        linkSkills: "Skills",
        linkPractice: "",
        linkContact: "Contact",
      },
      hero: {
        edition: "HI, I'M",
        specialization: "FULL STACK WEB DEVELOPER",
        location: "Turning Ideas into Digital Solutions",
        roleTag: "FULL STACK WEB DEVELOPER",
        name: "Muhammad Waqar",
        bio: "I build modern, scalable and high-performance web applications that solve real problems and deliver great user experiences.",
        buttonPrimary: "View My Projects →",
        buttonSecondary: "Get In Touch",
        currentFocus: "Turning Ideas into Digital Solutions",
        coreStack: "React, Node.js, Express, MongoDB, Tailwind CSS, Next.js",
        philosophy: "Building quality web experiences with clean code, intuitive user interfaces, and attention to detail.",
        status: "Available for Freelance & Full-time Roles",
      },
      about: {
        tagline: "ABOUT ME ────",
        heading: "Building quality web experiences with code and creativity.",
        paragraph1: "I'm a passionate Full Stack Web Developer who loves turning ideas into real, functional and user-friendly web applications. I enjoy working with modern technologies and constantly learning new skills to stay ahead.",
        paragraph2: "",
        badge1: "Clean Code",
        badge2: "Problem Solver",
        badge3: "Team Player",
        profileName: "Muhammad Waqar",
        profileLocation: "Pakistan",
        profileEmail: "muhammadwaqar7615@gmail.com",
        profileExperience: "1+ Year (Freelance / Personal Projects)",
      },
      skills: {
        tagline: "MY SKILLS ────",
        heading: "Technologies I Work With",
        subtext: "I work with modern technologies to build web applications from frontend to backend.",
      },
      sectionHeaders: {
        projectsTagline: "MY PROJECTS ────",
        projectsHeading: "Some Things I've Built",
        projectsButton: "View All Projects →",
        contactTagline: "GET IN TOUCH",
        contactHeading: "Let's work together",
        contactSubtext: "I'm always open to discussing new projects, creative ideas or opportunities. Feel free to reach out!",
        experienceTagline: "CAREER TIMELINE ────",
        experienceHeading: "Work Experience",
        educationTagline: "ACADEMIC BACKGROUND ────",
        educationHeading: "Education & Credentials",
        skillsTagline: "MY SKILLS ────",
        skillsHeading: "Technologies I Work With",
      },
      goals: {
        tagline: "LOOKING AHEAD",
        heading: "Continuously Learning & Expanding Capabilities",
        paragraph1: "Constantly exploring cutting-edge web technologies, performance optimization patterns, and modern database architectures.",
        commitment: "COMMITTED TO: Clean code · 60fps performance · Responsive layouts · Exceptional user experience.",
      },
      footer: {
        builtWithText: "© 2025 Muhammad Waqar. All rights reserved.",
      },
    },
  },
};

export const DEFAULT_THEME = {
  presetId: "preset-1",
  status: "published",
  colors: {
    primary: "#090A0F",
    accent: "#38BDF8",
    background: "#090A0F",
    text: "#F8FAFC",
    headingColor: "#FFFFFF",
    cardBg: "#0C0E14",
  },
  lightColors: DEFAULT_LIGHT_COLORS,
  content: DEFAULT_CONTENT,
  typography: {
    headingFont: "Space Grotesk",
    bodyFont: "Inter",
  },
  radius: "soft",
  spacing: "cozy",
  sections: DEFAULT_SECTIONS,
  history: [],
};

export const FONT_VARIABLE_MAP = {
  "Inter": "var(--font-inter), sans-serif",
  "Space Grotesk": "var(--font-space-grotesk), sans-serif",
  "Playfair Display": "var(--font-playfair-display), serif",
  "DM Serif Display": "var(--font-dm-serif-display), serif",
  "Manrope": "var(--font-manrope), sans-serif",
  "Merriweather": "var(--font-merriweather), serif",
  "Roboto": "var(--font-roboto), sans-serif",
  "Open Sans": "var(--font-open-sans), sans-serif",
  "Lato": "var(--font-lato), sans-serif",
  "Montserrat": "var(--font-montserrat), sans-serif",
  "Poppins": "var(--font-poppins), sans-serif",
  "Nunito": "var(--font-nunito), sans-serif",
  "Raleway": "var(--font-raleway), sans-serif",
  "DM Sans": "var(--font-dm-sans), sans-serif",
  "Outfit": "var(--font-outfit), sans-serif",
  "Plus Jakarta Sans": "var(--font-plus-jakarta-sans), sans-serif",
};
